var level=0;//this is to increment the level of the player
var start=0;//this is to recognize if the player has started the game or not. If he/she has started there must no longer be keydown events
var buttonColours=["red","blue","green","yellow"];
var gamePattern=[];//pattern which the user has to click
var userClickedPattern=[];//pattern which the user clicks
$(document).keydown(function(){
  if(start==0)
  {
    $("#level-title").text("Level "+level);
    nextSequence();
    start=1;
  }
})
$(".btn").click(function()
{
  var userChosenColour=$(this).attr("id");
  userClickedPattern.push(userChosenColour);
  playSound(userChosenColour);
  animatePress(userChosenColour);
  checkAnswer(userClickedPattern.length-1);
})//function to play the respective sound and play the animation on clicking a button
function nextSequence()//the next sequence which the user has to follow will be generated by palying random sounds
{
  userClickedPattern=[];//in each call the userClickedPattern becomes empty as the user has to enter the inputs again from the top
  level++;
  $("#level-title").text("Level " + level);
  var randomNumber = Math.floor(Math.random() * 4);
  var randomChosenColour = buttonColours[randomNumber];
  gamePattern.push(randomChosenColour);
  $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
  playSound(randomChosenColour);
}
function playSound(name)//plays the sounds
{
  var audio=new Audio("sounds/"+name+".mp3");
  audio.play();
}
function animatePress(currentColour)//animates the button
{
  $("#"+currentColour).addClass("pressed");
  setTimeout(function(){
    $("#"+currentColour).removeClass("pressed");
  },100);
}
function checkAnswer(currentLevel)//checks the answer on each click of the user
{
  if(gamePattern[currentLevel]==userClickedPattern[currentLevel])//If the latest answer is right then the length of the arrays are compared. This is because all the previous answers are already checked. If the user enters any extra stuff or has missed anything it gets noted
  {
    console.log("Success");
    if(gamePattern.length===userClickedPattern.length)
    {
      setTimeout(function(){
        nextSequence();
      },1000);
    }
  }
  else
  {
    $("#level-title").text("Wrong answer! Press any key");
    var audio1=new Audio("sounds/wrong.mp3");//plays the audio to let the user know his/her input was wrong
    audio1.play();
    $("body").addClass("game-over");
    setTimeout(function(){
      $("body").removeClass("game-over");
    },200);
    startOver();
  }
}
function startOver()
{
    level=0;
    gamePattern=[];
    started=0;
}
